import Head from "next/head";
import Hero from "../components/Hero";
import { TechStack } from "../components/TechStack";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tahir Ahmed T</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/website-icon.svg" />
      </Head>
      <Hero />
      <TechStack />
    </div>
  );
}
